apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: ns-label-tester
  namespace: default
  annotations:
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-namespace
        spec:
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: label-tester
                  annotations:
                    test: let-us-test-if-its-picked-up-by-prom
                  labels:
                    avs: this_is_avs
                    dept: this_is_dept
                    par: this_is_par
                    sdg: this_is_sdg
          remediationAction: enforce
          severity: low
  remediationAction: enforce
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: ns-label-tester-placement
  namespace: default
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: name
        operator: In
        values:
          - local-cluster
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: ns-label-tester-placement
  namespace: default
placementRef:
  name: ns-label-tester-placement
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
  - name: ns-label-tester
    apiGroup: policy.open-cluster-management.io
    kind: Policy
